#!/usr/bin/env python3
"""Generates build/test/generated.luau for the headless smoke test (tests/smoke.spec.luau).

It embeds:
  * every Luau source under src/ with its Rojo DataModel path (the luau CLI has no file IO),
  * the Roblox class hierarchy + member names and every Enum item, parsed from the luau-lsp
    definitions (~/luau-defs/globalTypes.d.luau), so the mock can reject invalid class names,
    property names and Enum items exactly like the engine does at runtime.
"""
import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DEFS = os.path.expanduser(os.environ.get("ROBLOX_DEFS", "~/luau-defs/globalTypes.d.luau"))
OUT_DIR = os.path.join(REPO, "build", "test")

# Rojo tree (default.project.json): filesystem root -> DataModel path.
ROOTS = [
    ("src/shared", ["ReplicatedStorage", "Shared"]),
    ("src/server", ["ServerScriptService", "Server"]),
    ("src/client", ["StarterPlayer", "StarterPlayerScripts", "Client"]),
]


def lua_str(s: str) -> str:
    level = 0
    while ("]" + "=" * level + "]") in s:
        level += 1
    eq = "=" * level
    return "[" + eq + "[\n" + s + "]" + eq + "]"


def collect_sources():
    out = []  # (dmPath list, className, source or None)
    for fs_root, dm_root in ROOTS:
        base = os.path.join(REPO, fs_root)
        out.append((dm_root, "Folder", None))
        for dirpath, dirnames, files in os.walk(base):
            dirnames.sort()
            rel = os.path.relpath(dirpath, base)
            dm_dir = dm_root + ([] if rel == "." else rel.split(os.sep))
            init = None
            for f in files:
                if f in ("init.luau", "init.server.luau", "init.client.luau"):
                    init = f
            if rel != ".":
                if init:
                    cls = "Script" if ".server." in init else "LocalScript" if ".client." in init else "ModuleScript"
                    out.append((dm_dir, cls, open(os.path.join(dirpath, init)).read()))
                else:
                    out.append((dm_dir, "Folder", None))
            for f in sorted(files):
                if not f.endswith(".luau") or f.startswith("init."):
                    continue
                name = f[: -len(".luau")]
                cls = "ModuleScript"
                if name.endswith(".server"):
                    name, cls = name[: -len(".server")], "Script"
                elif name.endswith(".client"):
                    name, cls = name[: -len(".client")], "LocalScript"
                out.append((dm_dir + [name], cls, open(os.path.join(dirpath, f)).read()))
    return out


def parse_defs():
    classes = {}  # name -> (super, {member: kind})
    enums = {}  # name -> [items]
    cur = None
    cur_enum = None
    for line in open(DEFS):
        # Older luau-lsp defs use `declare class X extends Y`; newer ones use
        # `declare extern type X extends Y with` (and root Instance at Object).
        m = re.match(r"^declare (?:class|extern type) (\w+)(?: extends (\w+))?", line)
        if m:
            name, sup = m.group(1), m.group(2)
            if name == "Instance":
                sup = None
            cur, cur_enum = None, None
            if name.startswith("Enum") and name.endswith("_INTERNAL"):
                cur_enum = name[len("Enum") : -len("_INTERNAL")]
                enums[cur_enum] = []
            elif sup is not None or name == "Instance":
                cur = name
                classes[name] = (sup, {})
            continue
        if line.startswith("end"):
            cur, cur_enum = None, None
            continue
        if cur_enum is not None:
            mm = re.match(r"^\s+(\w+):", line)
            if mm:
                enums[cur_enum].append(mm.group(1))
            continue
        if cur is not None:
            mm = re.match(r"^\s+function (\w+)\(", line)
            if mm:
                classes[cur][1][mm.group(1)] = "m"
                continue
            mm = re.match(r"^\s+(\w+): (.+)$", line)
            if mm:
                typ = mm.group(2).strip()
                kind = "e" if typ.startswith("RBXScriptSignal") else typ
                classes[cur][1][mm.group(1)] = kind
    # Keep only Instance subclasses.
    def is_instance(n):
        seen = set()
        while n and n not in seen:
            if n == "Instance":
                return True
            seen.add(n)
            n = classes.get(n, (None,))[0]
        return False

    classes = {k: v for k, v in classes.items() if is_instance(k)}
    return classes, enums


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    classes, enums = parse_defs()
    parts = ["--!nocheck", "-- GENERATED by tests/tools/bundle.py. Do not edit.", "local G = {}"]
    parts.append("G.Sources = {")
    for dm, cls, src in collect_sources():
        path = "{" + ", ".join('"%s"' % p for p in dm) + "}"
        if src is None:
            parts.append("\t{ Path = %s, Class = \"%s\" }," % (path, cls))
        else:
            parts.append("\t{ Path = %s, Class = \"%s\", Source = %s }," % (path, cls, lua_str(src)))
    parts.append("}")
    parts.append("G.Classes = {")
    for name, (sup, members) in sorted(classes.items()):
        mem = ", ".join('["%s"] = %s' % (k, lua_str(v) if "]" in v else '"%s"' % v) for k, v in sorted(members.items()))
        parts.append('\t["%s"] = { Super = %s, Members = { %s } },' % (name, '"%s"' % sup if sup else "nil", mem))
    parts.append("}")
    parts.append("G.Enums = {")
    for name, items in sorted(enums.items()):
        parts.append('\t["%s"] = { %s },' % (name, ", ".join('"%s"' % i for i in items)))
    parts.append("}")
    parts.append("return G")
    path = os.path.join(OUT_DIR, "generated.luau")
    with open(path, "w") as f:
        f.write("\n".join(parts) + "\n")
    print("wrote", os.path.relpath(path, REPO), "(%d classes, %d enums)" % (len(classes), len(enums)))
    write_review_bundle()


# Production-integration review (tests/production-review.spec.luau): the review-only sources at
# their expansion1-production-review.project.json paths, plus the project files' text and the
# src/server children, so the spec can check that default.project.json maps none of it.
REVIEW_FILES = [
    (["ServerScriptService", "ProductionReview"], "Folder", None),
    (["ServerScriptService", "ProductionReview", "Boot"], "Script", "tools/expansion1/production-review/Boot.server.luau"),
    (["ServerScriptService", "ProductionReview", "ReviewBoot"], "ModuleScript", "tools/expansion1/production-review/ReviewBoot.luau"),
]


def write_review_bundle():
    def read(rel):
        with open(os.path.join(REPO, rel), encoding="utf-8") as f:
            return f.read()

    parts = ["--!nocheck", "-- GENERATED by tests/tools/bundle.py. Do not edit.", "local R = {}", "R.Sources = {"]
    for dm, cls, rel in REVIEW_FILES:
        path = "{" + ", ".join('"%s"' % p for p in dm) + "}"
        if rel is None:
            parts.append('\t{ Path = %s, Class = "%s" },' % (path, cls))
        else:
            parts.append('\t{ Path = %s, Class = "%s", Source = %s },' % (path, cls, lua_str(read(rel))))
    parts.append("}")
    parts.append("R.DefaultProject = " + lua_str(read("default.project.json")))
    parts.append("R.ReviewProject = " + lua_str(read("expansion1-production-review.project.json")))
    children = sorted(os.listdir(os.path.join(REPO, "src", "server")))
    parts.append("R.ServerChildren = { " + ", ".join('"%s"' % c for c in children) + " }")
    parts.append("return R")
    path = os.path.join(OUT_DIR, "production-review.luau")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")
    print("wrote", os.path.relpath(path, REPO))


if __name__ == "__main__":
    sys.exit(main())
